apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-test-storageclass2
parameters:
  location: northeurope
  skuName: Standard_LRS
  storageAccount: azure_storage_account_test
provisioner: kubernetes.io/azure-file
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate